### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by patrickpoirier51** [djnugent/VisNav#3]
api start /home/patrick/visnav/PrecisionLand.py
GUIDED> Connecting to vehicle...
Vehicle connected!
Running Precision_Land
Using simulator
Frame 0
Exception in APIThread-1: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/droneapi/module/api.py", line 329, in run
    self.fn()
  File "/usr/local/lib/python2.7/dist-packages/droneapi/module/api.py", line 600, in <lambda>
    APIThread(self, lambda: execfile(args[1], g), args[1])
  File "/home/patrick/visnav/PrecisionLand.py", line 248, in <module>
    strat.run()
  File "/home/patrick/visnav/PrecisionLand.py", line 208, in run
    VN_logger.text(VN_logger.DEBUG, 'Rings detected: {0}'.format(len(results[4])))
TypeError: object of type 'NoneType' has no len()

**Comment by patrickpoirier51** [comment]
changed line 208 to this:
VN_logger.text(VN_logger.DEBUG, 'Rings detected: {0}'.format(results[4]))

**Comment by patrickpoirier51** [comment]
still got this error when frame is detected:
  File "/home/patrick/visnav/PrecisionLand.py", line 192, in run
    imageQueue.remove(f)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by moonsummer** [comment]
Running script (/home/farsight/.mavinit.scr)
Failed to load module: No module named droneapi.module.api. Use 'set moddebug 3' in the MAVProxy console to enable traceback
Failed to load module: No module named droneapi.module.api. Use 'set moddebug 3' in the MAVProxy console to enable traceback
Log Directory: 
Telemetry log: mav.tlog
Waiting for heartbeat from tcp:127.0.0.1:5760
 MAV> STABILIZE> 
STABILIZE> 
STABILIZE> Received 555 parameters
Saved 555 parameters to mav.parm

STABILIZE> 
STABILIZE> 
STABILIZE> 
@patrickpoirier51
